version: "3.8"

services:
# =========================
# FRONTEND
# =========================
# svelte kit main frontend app
  svelte-app-svc:
    build:
      context: ./MAIN-CLIENT-svelte/.
      dockerfile: Dockerfile
    container_name: MAIN-CLIENT-svelte
    ports:
      - "80:3000"
    networks:
      - "cloud-netwerk"
# =========================
# DATABASES
# =========================
# mongodb database voor algemene data
  mongo-db-svc:
    image: mongo
    restart: always
    container_name: DB-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_root
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    # expose:
    #   - "27017"
    ports: # DEBUG
      - "27017:27017"
    networks:
      - "cloud-netwerk"
# mysql database voor user data
  users-db-mysql-svc:
    image: mysql:9.1.0
    restart: always
    container_name: DB-mysql
    environment:
      MYSQL_USER: "mysql_root"
      MYSQL_PASSWORD: "mysql123"
      MYSQL_ROOT_PASSWORD: "mysql123"
      MYSQL_DATABASE: "cloud_project_db"
    # expose:
    #  - "3306"
    ports: # DEBUG
      - "3306:3306"
    networks:
      - "cloud-netwerk"
# =========================
# DATABASE CLIENTS  
# =========================
# mongodb
  mongo-express-svc:
    image: mongo-express
    restart: always
    container_name: CLIENT-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo123
      ME_CONFIG_MONGODB_URL: mongodb://mongo_root:mongo123@mongo-db-svc:27017/
      ME_CONFIG_SITE_BASEURL: /proxy/mongo
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "123"
      ME_CONFIG_BASICAUTH: true
    ports:
      - "8081:8081"
    networks:
      - "cloud-netwerk"
# mysql
  adminer-svc:
    image: adminer
    restart: always
    container_name: CLIENT-mysql
    ports:
      - "8080:8080"
    networks:
      - "cloud-netwerk"
# =========================
# GATEWAY API'S  
# =========================
  rest-gateway-svc:
    build:
      context: ./GATEWAY-rest/.
      dockerfile: Dockerfile
    container_name: GATEWAY-rest
    ports:
      - "3001:3001"
    networks:
      - "cloud-netwerk"
# =========================
# MICROSERVICE API'S  
# =========================
  # auth-rest-svc:
  #   build:
  #     context: ./MICRO-auth-rest
  #     dockerfile: Dockerfile
  #   container_name: MICRO-auth-rest
  #   expose:
  #    - "3003"
  #   ports: # DEBUG
  #     - "3003:3003"
  # networks:
  # - "cloud-netwerk"
  userdb-graphql-svc:
    build:
      context: ./MICRO-userdb-graphql
      dockerfile: Dockerfile
    container_name: MICRO-userdb-graphql
    expose:
      - "3002"
    ports: # DEBUG
      - "3002:3002"
    networks:
      - "cloud-netwerk"

networks:
  cloud-netwerk:
volumes:
  mysql-data: