# version: "3.8"

services:
# =========================
# FRONTEND
# =========================
# svelte kit main frontend app
  client-svc:
    build:
      context: "./CLIENT/."
      dockerfile: Dockerfile
    container_name: CLIENT
    ports:
      - "80:3000"
    networks:
      - "cloud-netwerk"
# =========================
# DATABASES
# =========================
# mongodb database voor algemene data
  db-mongo:
    image: mongo
    restart: always
    container_name: DB-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_root
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    # expose:
    #   - "27017"
    ports: # DEBUG
      - "27017:27017"
    networks:
      - "cloud-netwerk"
    attach: false # ik hoef geen console logs te zien
# mysql database voor user data
  db-mysql:
    image: mysql:9.1.0
    restart: always
    container_name: DB-mysql
    environment:
      MYSQL_USER: "mysql_root"
      MYSQL_PASSWORD: "mysql123"
      MYSQL_ROOT_PASSWORD: "mysql123"
      MYSQL_DATABASE: "cloud_project_db"
    # expose:
    #  - "3306"
    ports: # DEBUG
      - "3306:3306"
    networks:
      - "cloud-netwerk"
    attach: false # ik hoef geen console logs te zien
# =========================
# DATABASE CLIENTS  
# =========================
# mongodb
  db-client-mongo:
    image: mongo-express
    restart: always
    container_name: DB_CLIENT-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo123
      ME_CONFIG_MONGODB_URL: mongodb://mongo_root:mongo123@db-mongo:27017/
      ME_CONFIG_SITE_BASEURL: /proxy/mongo
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "123"
      ME_CONFIG_BASICAUTH: true
    ports:
      - "8081:8081"
    networks:
      - "cloud-netwerk"
    attach: false # ik hoef geen console logs te zien
# mysql
  db-client-mysql:
    image: adminer
    restart: always
    container_name: DB_CLIENT-mysql
    ports:
      - "8080:8080"
    networks:
      - "cloud-netwerk"
    attach: false # ik hoef geen console logs te zien
# =========================
# CORE MICROSERVICES 
# =========================
  core-apapter-rest:
    build:
      context: "./CORE_ADAPTER - rest"
      dockerfile: Dockerfile
    container_name: CORE_ADAPTER-REST
    ports:
      - "3001:3001"
    networks:
      - "cloud-netwerk"
# =========================
# APP MICROSERVICES  
# =========================
  app-auth-rest:
    build:
      context: "./APP_AUTH - rest"
      dockerfile: Dockerfile
    container_name: APP_AUTH-REST
    # expose:
    #  - "3003"
    ports: # DEBUG
      - "3003:3003"
    networks:
      - "cloud-netwerk"
  app-userdb-graphql:
    build:
      context: "./APP_USERDB - graphql"
      dockerfile: Dockerfile
    container_name: APP_USERDB-GRAPHQL
    expose:
      - "3002"
    ports: # DEBUG
      - "3002:3002"
    networks:
      - "cloud-netwerk"

networks:
  cloud-netwerk:
volumes:
  mysql-data: