// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: facade.proto

package protobuf_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Facade_Coordinate_FullMethodName = "/facade_service.Facade/Coordinate"
)

// FacadeClient is the client API for Facade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service definition
type FacadeClient interface {
	Coordinate(ctx context.Context, in *GrpcRequest, opts ...grpc.CallOption) (*GrpcResponse, error)
}

type facadeClient struct {
	cc grpc.ClientConnInterface
}

func NewFacadeClient(cc grpc.ClientConnInterface) FacadeClient {
	return &facadeClient{cc}
}

func (c *facadeClient) Coordinate(ctx context.Context, in *GrpcRequest, opts ...grpc.CallOption) (*GrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrpcResponse)
	err := c.cc.Invoke(ctx, Facade_Coordinate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacadeServer is the server API for Facade service.
// All implementations must embed UnimplementedFacadeServer
// for forward compatibility.
//
// gRPC service definition
type FacadeServer interface {
	Coordinate(context.Context, *GrpcRequest) (*GrpcResponse, error)
	mustEmbedUnimplementedFacadeServer()
}

// UnimplementedFacadeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFacadeServer struct{}

func (UnimplementedFacadeServer) Coordinate(context.Context, *GrpcRequest) (*GrpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Coordinate not implemented")
}
func (UnimplementedFacadeServer) mustEmbedUnimplementedFacadeServer() {}
func (UnimplementedFacadeServer) testEmbeddedByValue()                {}

// UnsafeFacadeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacadeServer will
// result in compilation errors.
type UnsafeFacadeServer interface {
	mustEmbedUnimplementedFacadeServer()
}

func RegisterFacadeServer(s grpc.ServiceRegistrar, srv FacadeServer) {
	// If the following call pancis, it indicates UnimplementedFacadeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Facade_ServiceDesc, srv)
}

func _Facade_Coordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServer).Coordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Facade_Coordinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServer).Coordinate(ctx, req.(*GrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Facade_ServiceDesc is the grpc.ServiceDesc for Facade service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Facade_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "facade_service.Facade",
	HandlerType: (*FacadeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Coordinate",
			Handler:    _Facade_Coordinate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facade.proto",
}
